name: Assign PR reviewers

on:
  pull_request:
    types: [ready_for_review]

jobs:
  assign-reviewers:
    uses: Travtus/.github/.github/workflows/auto_assign_template.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.PAT_GITHUB }}
